# test on Ubuntu
name: ubuntu

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        cuda: ["10.2.89", "11.0.3"]

    env:
      build_dir: "build"
      config: "Release"

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install BLAS & LAPACK
        run: sudo apt-get install libblas-dev liblapack-dev

      - name: Install SuiteSparse dependencies
        run: sudo apt-get install libgmp3-dev libmpc-dev

      - name: Cache SuiteSparse
        uses: actions/cache@v2
        id: suitesparse
        with:
          path: ~/suitesparse
          key: ${{ matrix.os }}-suitesparse

      - name: Install SuiteSparse
        env:
          CACHE_HIT: ${{ steps.suitesparse.outputs.cache-hit }}
        run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --verbose --force --recursive ~/suitesparse /usr/local/suitesparse
          else
            source ./scripts/actions/install_suitesparse.sh
          fi

      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.5
        id: cuda-toolkit
        with:
          cuda: ${{ matrix.cuda }}

      - run: |
          echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
          echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
          nvcc -V

      - name: Cache SUNDIALS
        uses: actions/cache@v2
        id: sundials
        with:
          path: ~/sundials
          key: ${{ matrix.os }}-sundials

      - name: Install SUNDIALS
        env:
          CACHE_HIT: ${{ steps.sundials.outputs.cache-hit }}
        run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --verbose --force --recursive ~/sundials /usr/local/sundials
          else
            source ./scripts/actions/install_sundials.sh
          fi

      - name: Build example
        run: |
          cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release \
              -DSUNDIALS_DIR=/usr/local/sundials/lib/cmake/sundials \
              -DCMAKE_CUDA_ARCHITECTURES=61 \
              -DMAKE_PYTHON=ON -DMAKE_TEST=ON
          cmake --build build

